### ISSUE TITLE
First bunch floating window - error when opening "Example - Edit First!" from Bunch menu bar.

### ISSUE THREAD

**Issue by loseth** [ttscoff/bunch-docs#159]
When the "First bunch" floating window is in the foreground (might also be when in the background) and one tries to open the "Example - Edit First" bunch from the Bunch menu bar, one gets an error. This error does not occur every time one tries this, I've experienced it 3 times out of 15 tries.
 
Error running AppleScript
There was an error running an AppleScript, it's possible the target application does not respond to the requested command: "tell app System Events" to set autohide of dock preferences to false"
More information in the Bunch Log.
Cancel Show Log

2021-10-18 09:51:59: 🔴{
    NSAppleScriptErrorBriefMessage = "Application isn\U2019t running.";
    NSAppleScriptErrorMessage = "Application isn\U2019t running.";
    NSAppleScriptErrorNumber = "-600";
    NSAppleScriptErrorRange = "NSRange: {28, 41}";
}

**Comment by ttscoff** [comment]
I'm not able to replicate this. The error seems to indicate that System 
Events isn't running, which I don't think is possible.

I assume you have "Toggle Bunches" disabled (which IIRC is the default 
when first installing), when you're doing this, correct?

Did you make any edits to the Example Bunch before launching it 15 more 
times?

-Brett
